version: '3'
services:
  web:
    image: nginx:1.16.0-alpine
    # container_name: web
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - laravel
  laravel:
    container_name: laravel
    build:
      context: docker/php-fpm-laravel
      dockerfile: php-fpm.docker
    links:
      - db
    volumes:
      - "./volumes/www:/usr/share/nginx/html"
  db:
    image: postgres:11.3-alpine
    # container_name: db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: "--locale=jp_JP.UTF8"
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"